# Generated by Django 4.2.9 on 2024-09-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
            ],
        ),
    ]
